# app/domains/items/schemas.py
# Gemini Assisted Code for Example

from pydantic import BaseModel, Field
from typing import Optional
from datetime import date

# 1. Base schema: Common fields
class ItemBase(BaseModel):
    ISBN: str
    BranchID: int
    CurrentBranchID: Optional[int]
    IsDamaged: Optional[int]
    Status: Optional[str]


# 2. Create schema: Used for POST
class ItemCreate(ItemBase):
    # ItemID is usually auto-generated by the database
    pass

# 3. Read schema: Used for GET
class ItemRead(ItemBase):
    ItemID: int  # DB-generated primary key

    class Config:
        from_attributes = True  # Enables ORM integration (replaces orm_mode in Pydantic v2)

# 4. Update schema: Used for PATCH
class ItemUpdate(BaseModel):
    ISBN: Optional[str]
    BranchID: Optional[int]
    IsDamaged: Optional[int]
    
# 5. Extended Read schema with related data for checked-out/checked-in lists
class ItemWithDetailsRead(BaseModel):
    ItemID: int
    ISBN: str
    BranchID: int
    IsDamaged: int
    # Include ItemDetails information
    Title: Optional[str] = None
    ItemTypeName: Optional[str] = None
    # Include Transaction information (for checked-out items)
    TransactionID: Optional[int] = None
    PatronID: Optional[int] = None
    PatronName: Optional[str] = None
    DateStart: Optional[date] = None
    DateDue: Optional[date] = None
    
    class Config:
        from_attributes = True